###Obtener todas las categorias
POST http://localhost:3000/api/categoria/obtener
Content-Type: application/json

{
    "accion":1,
    "filtro":{
  "clave": "CATROPA"
}
}

###Obtener todas las categorias
POST https://productosbacktorres.fly.dev/api/categoria/obtener
Content-Type: application/json

{
    "accion":1,
    "filtro":{
  "clave": "CATROPA"
}
}

###Gestionar categorias
POST http://localhost:3000/api/categoria/gestionar
Content-Type: application/json

{
    "accion":1,
    "categoria":{
  "nombre": "Jardineria",
  "clave": "CATJARDI",
  "descripcion": "Articulos para jardineria.",
  "fecha_alta": "2023-10-26T12:00:00Z"
}
}