###Obtener todas las imagenes
GET http://localhost:3000/api/image

###Obtener todas imagenes de un producto
GET http://localhost:3000/api/image/producto
Content-Type: application/json

{
    "claveProducto":"PROD003"
}

###Obtener todas imagenes de un producto
POST https://productosbacktorres.fly.dev/api/image/producto
Content-Type: application/json

{
    "claveProducto":"PROD003"
}

###Insertar imagenes
POST http://localhost:3000/api/image
Content-Type: application/json

{
    "claveProducto":"The great atractor",
    "imgB64":["Imagen1","Imagen2","Imagen3"]
}

###Eliminar imagenes
DELETE http://localhost:3000/api/image
Content-Type: application/json

{
    "claveProducto":"Producto1"
}

###Actualizar imagenes
PUT http://localhost:3000/api/image
Content-Type: application/json

{
    "claveProducto":"Producto1",
    "imgB64":["Imagen4","Imagen5","Imagen6"]
}