###Obtener todos los productos
POST http://localhost:3000/api/producto/obtener
Content-Type: application/json

{
    "accion":2,
    "filtro":{
  "id_categoria": 2
}
}


###Obtener todos los productos
POST https://productosbacktorres.fly.dev/api/producto/obtener
Content-Type: application/json

{
    "accion":2,
    "filtro":{
  "id_cliente": 7
}
}

###Gestionar productos
POST https://productosbacktorres.fly.dev/api/producto/gestionar
Content-Type: application/json

{
    "accion":1,
    "producto":{
  "clave": "P465001",
  "nombre": "Portátil de Alto Rendimiento",
  "precio": 1299.99,
  "descripcion": "Portátil con procesador potente y gráficos de alta calidad.",
  "stock": 50,
  "fecha_alta": "2023-10-26T12:00:00Z",
  "fecha_modificacion": "2023-10-28T12:00:00Z",
  "baja_logica": false,
  "marca": "MarcaD",
  "id_categoria": [2],
  "id_usuario": 1
}
}